// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EscalateRequest {
    #[prost(string, tag="1")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub reason: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub context_summary: ::prost::alloc::string::String,
    #[prost(enumeration="EscalationUrgency", tag="4")]
    pub urgency: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EscalateResponse {
    #[prost(string, tag="1")]
    pub escalation_id: ::prost::alloc::string::String,
    #[prost(enumeration="EscalationState", tag="2")]
    pub state: i32,
    #[prost(message, optional, tag="3")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ResolveEscalationRequest {
    #[prost(string, tag="1")]
    pub escalation_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub resolution: ::prost::alloc::string::String,
    #[prost(bool, tag="3")]
    pub approved: bool,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ResolveEscalationResponse {
    #[prost(bool, tag="1")]
    pub accepted: bool,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum EscalationUrgency {
    Unspecified = 0,
    Low = 1,
    Medium = 2,
    High = 3,
    Critical = 4,
}
impl EscalationUrgency {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "ESCALATION_URGENCY_UNSPECIFIED",
            Self::Low => "LOW",
            Self::Medium => "MEDIUM",
            Self::High => "HIGH",
            Self::Critical => "CRITICAL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ESCALATION_URGENCY_UNSPECIFIED" => Some(Self::Unspecified),
            "LOW" => Some(Self::Low),
            "MEDIUM" => Some(Self::Medium),
            "HIGH" => Some(Self::High),
            "CRITICAL" => Some(Self::Critical),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum EscalationState {
    Unspecified = 0,
    Open = 1,
    Acknowledged = 2,
    Resolved = 3,
    TimedOut = 4,
}
impl EscalationState {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "ESCALATION_STATE_UNSPECIFIED",
            Self::Open => "OPEN",
            Self::Acknowledged => "ACKNOWLEDGED",
            Self::Resolved => "RESOLVED",
            Self::TimedOut => "TIMED_OUT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ESCALATION_STATE_UNSPECIFIED" => Some(Self::Unspecified),
            "OPEN" => Some(Self::Open),
            "ACKNOWLEDGED" => Some(Self::Acknowledged),
            "RESOLVED" => Some(Self::Resolved),
            "TIMED_OUT" => Some(Self::TimedOut),
            _ => None,
        }
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CheckGuardrailRequest {
    #[prost(string, tag="1")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub proposed_action: ::prost::alloc::string::String,
    #[prost(enumeration="super::telemetry::PermissionLevel", tag="3")]
    pub permission_level: i32,
    #[prost(string, tag="4")]
    pub risk_context: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CheckGuardrailResponse {
    #[prost(enumeration="GuardrailVerdict", tag="1")]
    pub verdict: i32,
    #[prost(string, tag="2")]
    pub reason: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="3")]
    pub policy_ids_triggered: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RegisterPolicyRequest {
    #[prost(string, tag="1")]
    pub policy_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub bundle_version: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="3")]
    pub policy_content: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RegisterPolicyResponse {
    #[prost(bool, tag="1")]
    pub accepted: bool,
    #[prost(string, tag="2")]
    pub effective_version: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum GuardrailVerdict {
    Unspecified = 0,
    Allow = 1,
    Block = 2,
    RequireApproval = 3,
}
impl GuardrailVerdict {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "GUARDRAIL_VERDICT_UNSPECIFIED",
            Self::Allow => "ALLOW",
            Self::Block => "BLOCK",
            Self::RequireApproval => "REQUIRE_APPROVAL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "GUARDRAIL_VERDICT_UNSPECIFIED" => Some(Self::Unspecified),
            "ALLOW" => Some(Self::Allow),
            "BLOCK" => Some(Self::Block),
            "REQUIRE_APPROVAL" => Some(Self::RequireApproval),
            _ => None,
        }
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TriggerInterventionRequest {
    #[prost(string, tag="1")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(enumeration="InterventionKind", tag="2")]
    pub kind: i32,
    #[prost(string, tag="3")]
    pub reason: ::prost::alloc::string::String,
    #[prost(enumeration="super::telemetry::AutonomyMode", tag="4")]
    pub downgrade_to: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct TriggerInterventionResponse {
    #[prost(string, tag="1")]
    pub intervention_id: ::prost::alloc::string::String,
    #[prost(bool, tag="2")]
    pub applied: bool,
    #[prost(message, optional, tag="3")]
    pub applied_at: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetInterventionStatusRequest {
    #[prost(string, tag="1")]
    pub intervention_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetInterventionStatusResponse {
    #[prost(string, tag="1")]
    pub intervention_id: ::prost::alloc::string::String,
    #[prost(enumeration="InterventionKind", tag="2")]
    pub kind: i32,
    #[prost(bool, tag="3")]
    pub active: bool,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum InterventionKind {
    Unspecified = 0,
    CircuitBreak = 1,
    Rollback = 2,
    AutonomyDowngrade = 3,
    ModelSwap = 4,
    HardStop = 5,
}
impl InterventionKind {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "INTERVENTION_KIND_UNSPECIFIED",
            Self::CircuitBreak => "CIRCUIT_BREAK",
            Self::Rollback => "ROLLBACK",
            Self::AutonomyDowngrade => "AUTONOMY_DOWNGRADE",
            Self::ModelSwap => "MODEL_SWAP",
            Self::HardStop => "HARD_STOP",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "INTERVENTION_KIND_UNSPECIFIED" => Some(Self::Unspecified),
            "CIRCUIT_BREAK" => Some(Self::CircuitBreak),
            "ROLLBACK" => Some(Self::Rollback),
            "AUTONOMY_DOWNGRADE" => Some(Self::AutonomyDowngrade),
            "MODEL_SWAP" => Some(Self::ModelSwap),
            "HARD_STOP" => Some(Self::HardStop),
            _ => None,
        }
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StartSessionRequest {
    #[prost(string, tag="1")]
    pub task_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub agent_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub tenant_id: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub environment: ::prost::alloc::string::String,
    #[prost(enumeration="super::telemetry::AutonomyMode", tag="5")]
    pub autonomy_mode: i32,
    #[prost(enumeration="super::telemetry::RiskTier", tag="6")]
    pub risk_tier: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StartSessionResponse {
    #[prost(string, tag="1")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag="2")]
    pub started_at: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EndSessionRequest {
    #[prost(string, tag="1")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(enumeration="super::telemetry::CompletionStatus", tag="2")]
    pub completion_status: i32,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct EndSessionResponse {
    #[prost(bool, tag="1")]
    pub accepted: bool,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateStateRequest {
    #[prost(string, tag="1")]
    pub session_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub state_key: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="3")]
    pub state_value: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateStateResponse {
    #[prost(bool, tag="1")]
    pub accepted: bool,
    #[prost(string, tag="2")]
    pub state_version: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
