// @generated
// This file is @generated by prost-build.
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum CompletionStatus {
    Unspecified = 0,
    Success = 1,
    Failure = 2,
    Partial = 3,
    Cancelled = 4,
    Timeout = 5,
}
impl CompletionStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "COMPLETION_STATUS_UNSPECIFIED",
            Self::Success => "SUCCESS",
            Self::Failure => "FAILURE",
            Self::Partial => "PARTIAL",
            Self::Cancelled => "CANCELLED",
            Self::Timeout => "TIMEOUT",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "COMPLETION_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "SUCCESS" => Some(Self::Success),
            "FAILURE" => Some(Self::Failure),
            "PARTIAL" => Some(Self::Partial),
            "CANCELLED" => Some(Self::Cancelled),
            "TIMEOUT" => Some(Self::Timeout),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum FailureCategory {
    Unspecified = 0,
    ToolError = 1,
    ModelError = 2,
    PolicyBlock = 3,
    LoopDetected = 4,
    TimeoutExceeded = 5,
    HumanCancelled = 6,
    ResourceExhausted = 7,
    ContextOverflow = 8,
}
impl FailureCategory {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "FAILURE_CATEGORY_UNSPECIFIED",
            Self::ToolError => "TOOL_ERROR",
            Self::ModelError => "MODEL_ERROR",
            Self::PolicyBlock => "POLICY_BLOCK",
            Self::LoopDetected => "LOOP_DETECTED",
            Self::TimeoutExceeded => "TIMEOUT_EXCEEDED",
            Self::HumanCancelled => "HUMAN_CANCELLED",
            Self::ResourceExhausted => "RESOURCE_EXHAUSTED",
            Self::ContextOverflow => "CONTEXT_OVERFLOW",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "FAILURE_CATEGORY_UNSPECIFIED" => Some(Self::Unspecified),
            "TOOL_ERROR" => Some(Self::ToolError),
            "MODEL_ERROR" => Some(Self::ModelError),
            "POLICY_BLOCK" => Some(Self::PolicyBlock),
            "LOOP_DETECTED" => Some(Self::LoopDetected),
            "TIMEOUT_EXCEEDED" => Some(Self::TimeoutExceeded),
            "HUMAN_CANCELLED" => Some(Self::HumanCancelled),
            "RESOURCE_EXHAUSTED" => Some(Self::ResourceExhausted),
            "CONTEXT_OVERFLOW" => Some(Self::ContextOverflow),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum AutonomyMode {
    Unspecified = 0,
    Supervised = 1,
    SemiAutonomous = 2,
    Autonomous = 3,
}
impl AutonomyMode {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "AUTONOMY_MODE_UNSPECIFIED",
            Self::Supervised => "SUPERVISED",
            Self::SemiAutonomous => "SEMI_AUTONOMOUS",
            Self::Autonomous => "AUTONOMOUS",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "AUTONOMY_MODE_UNSPECIFIED" => Some(Self::Unspecified),
            "SUPERVISED" => Some(Self::Supervised),
            "SEMI_AUTONOMOUS" => Some(Self::SemiAutonomous),
            "AUTONOMOUS" => Some(Self::Autonomous),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum RiskTier {
    Unspecified = 0,
    Low = 1,
    Medium = 2,
    High = 3,
    Critical = 4,
}
impl RiskTier {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "RISK_TIER_UNSPECIFIED",
            Self::Low => "LOW",
            Self::Medium => "MEDIUM",
            Self::High => "HIGH",
            Self::Critical => "CRITICAL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "RISK_TIER_UNSPECIFIED" => Some(Self::Unspecified),
            "LOW" => Some(Self::Low),
            "MEDIUM" => Some(Self::Medium),
            "HIGH" => Some(Self::High),
            "CRITICAL" => Some(Self::Critical),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum PermissionLevel {
    Unspecified = 0,
    ReadOnly = 1,
    ReadWrite = 2,
    Privileged = 3,
    System = 4,
}
impl PermissionLevel {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "PERMISSION_LEVEL_UNSPECIFIED",
            Self::ReadOnly => "READ_ONLY",
            Self::ReadWrite => "READ_WRITE",
            Self::Privileged => "PRIVILEGED",
            Self::System => "SYSTEM",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "PERMISSION_LEVEL_UNSPECIFIED" => Some(Self::Unspecified),
            "READ_ONLY" => Some(Self::ReadOnly),
            "READ_WRITE" => Some(Self::ReadWrite),
            "PRIVILEGED" => Some(Self::Privileged),
            "SYSTEM" => Some(Self::System),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ToolResultStatus {
    Unspecified = 0,
    ToolSuccess = 1,
    ToolFailure = 2,
    ToolTimeout = 3,
    ToolPermissionDenied = 4,
}
impl ToolResultStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "TOOL_RESULT_STATUS_UNSPECIFIED",
            Self::ToolSuccess => "TOOL_SUCCESS",
            Self::ToolFailure => "TOOL_FAILURE",
            Self::ToolTimeout => "TOOL_TIMEOUT",
            Self::ToolPermissionDenied => "TOOL_PERMISSION_DENIED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TOOL_RESULT_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "TOOL_SUCCESS" => Some(Self::ToolSuccess),
            "TOOL_FAILURE" => Some(Self::ToolFailure),
            "TOOL_TIMEOUT" => Some(Self::ToolTimeout),
            "TOOL_PERMISSION_DENIED" => Some(Self::ToolPermissionDenied),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum AttributeType {
    Unspecified = 0,
    String = 1,
    Int64 = 2,
    Double = 3,
    Bool = 4,
    Bytes = 5,
    StringArray = 6,
}
impl AttributeType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "ATTRIBUTE_TYPE_UNSPECIFIED",
            Self::String => "STRING",
            Self::Int64 => "INT64",
            Self::Double => "DOUBLE",
            Self::Bool => "BOOL",
            Self::Bytes => "BYTES",
            Self::StringArray => "STRING_ARRAY",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ATTRIBUTE_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "STRING" => Some(Self::String),
            "INT64" => Some(Self::Int64),
            "DOUBLE" => Some(Self::Double),
            "BOOL" => Some(Self::Bool),
            "BYTES" => Some(Self::Bytes),
            "STRING_ARRAY" => Some(Self::StringArray),
            _ => None,
        }
    }
}
/// VersionLineage carries the full software bill-of-materials for a run.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct VersionLineage {
    #[prost(string, tag="1")]
    pub agent_version: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub model_name: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub model_version: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub prompt_version: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub toolchain_version: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub memory_version: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub retrieval_version: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub policy_bundle_version: ::prost::alloc::string::String,
}
/// AgentEvent is the canonical envelope for every event emitted by an agent.
/// Maps to an OTel span with routeiq.* attributes (see conventions/telemetry.yaml).
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AgentEvent {
    #[prost(bytes="vec", tag="1")]
    pub trace_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="2")]
    pub span_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(bytes="vec", tag="3")]
    pub parent_span_id: ::prost::alloc::vec::Vec<u8>,
    #[prost(message, optional, tag="4")]
    pub timestamp: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(enumeration="EventType", tag="5")]
    pub event_type: i32,
    #[prost(string, tag="6")]
    pub tenant_id: ::prost::alloc::string::String,
    #[prost(string, tag="7")]
    pub environment: ::prost::alloc::string::String,
    #[prost(string, tag="8")]
    pub task_id: ::prost::alloc::string::String,
    #[prost(string, tag="9")]
    pub run_id: ::prost::alloc::string::String,
    #[prost(string, tag="10")]
    pub step_id: ::prost::alloc::string::String,
    #[prost(string, tag="11")]
    pub agent_id: ::prost::alloc::string::String,
    #[prost(string, tag="12")]
    pub agent_role: ::prost::alloc::string::String,
    #[prost(string, tag="13")]
    pub workflow_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag="14")]
    pub versions: ::core::option::Option<VersionLineage>,
    #[prost(enumeration="AutonomyMode", tag="15")]
    pub autonomy_mode: i32,
    #[prost(enumeration="RiskTier", tag="16")]
    pub risk_tier: i32,
    #[prost(oneof="agent_event::Payload", tags="100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110")]
    pub payload: ::core::option::Option<agent_event::Payload>,
}
/// Nested message and enum types in `AgentEvent`.
pub mod agent_event {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Payload {
        #[prost(message, tag="100")]
        Task(super::TaskEvent),
        #[prost(message, tag="101")]
        Step(super::StepEvent),
        #[prost(message, tag="102")]
        Decision(super::DecisionEvent),
        #[prost(message, tag="103")]
        ToolCall(super::ToolCallEvent),
        #[prost(message, tag="104")]
        Retrieval(super::RetrievalEvent),
        #[prost(message, tag="105")]
        Memory(super::MemoryEvent),
        #[prost(message, tag="106")]
        Handoff(super::HandoffEvent),
        #[prost(message, tag="107")]
        Policy(super::PolicyEvent),
        #[prost(message, tag="108")]
        Intervention(super::InterventionEvent),
        #[prost(message, tag="109")]
        Recovery(super::RecoveryEvent),
        #[prost(message, tag="110")]
        StateSnapshot(super::StateSnapshotEvent),
    }
}
/// TaskEvent carries the outcome of a complete agent task.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct TaskEvent {
    #[prost(string, tag="1")]
    pub input_intent: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub normalized_task_type: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub expected_outcome: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub actual_outcome: ::prost::alloc::string::String,
    #[prost(enumeration="CompletionStatus", tag="5")]
    pub completion_status: i32,
    #[prost(enumeration="FailureCategory", tag="6")]
    pub failure_category: i32,
    #[prost(double, tag="7")]
    pub total_cost_usd: f64,
    #[prost(int64, tag="8")]
    pub total_tokens: i64,
    #[prost(bool, tag="9")]
    pub human_escalated: bool,
    #[prost(bool, tag="10")]
    pub rolled_back: bool,
    #[prost(string, tag="11")]
    pub cohort: ::prost::alloc::string::String,
}
/// ToolCallEvent records a single tool invocation within a step.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ToolCallEvent {
    #[prost(string, tag="1")]
    pub tool_name: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub tool_version: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub arguments_hash: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub arguments_summary: ::prost::alloc::string::String,
    #[prost(enumeration="PermissionLevel", tag="5")]
    pub permission_level: i32,
    #[prost(message, optional, tag="6")]
    pub start_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag="7")]
    pub end_time: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(double, tag="8")]
    pub latency_ms: f64,
    #[prost(enumeration="ToolResultStatus", tag="9")]
    pub result_status: i32,
    #[prost(string, tag="10")]
    pub error_code: ::prost::alloc::string::String,
    #[prost(string, tag="11")]
    pub result_summary: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="12")]
    pub result_quality_flags: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// StepEvent captures the outcome of a single reasoning step within a task run.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StepEvent {
    #[prost(string, tag="1")]
    pub selected_action: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub action_rationale: ::prost::alloc::string::String,
    #[prost(enumeration="CompletionStatus", tag="3")]
    pub completion_status: i32,
    #[prost(enumeration="FailureCategory", tag="4")]
    pub failure_category: i32,
    #[prost(int32, tag="5")]
    pub step_index: i32,
    #[prost(int32, tag="6")]
    pub retry_count: i32,
}
/// DecisionEvent records a branching decision point — which path or tool the agent chose.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct DecisionEvent {
    /// "tool_selection" | "path_choice" | "escalation_check"
    #[prost(string, tag="1")]
    pub decision_type: ::prost::alloc::string::String,
    /// JSON or natural-language summary of alternatives
    #[prost(string, tag="2")]
    pub options_considered: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub chosen_option: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub rationale: ::prost::alloc::string::String,
    /// 0.0–1.0 model-reported confidence
    #[prost(double, tag="5")]
    pub confidence: f64,
}
/// RetrievalEvent records a RAG, search, or knowledge-base lookup.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct RetrievalEvent {
    /// "vector" | "keyword" | "hybrid" | "graph"
    #[prost(string, tag="1")]
    pub retrieval_type: ::prost::alloc::string::String,
    /// sanitized query — PII redacted by collector
    #[prost(string, tag="2")]
    pub query_summary: ::prost::alloc::string::String,
    #[prost(int32, tag="3")]
    pub results_count: i32,
    #[prost(double, tag="4")]
    pub top_score: f64,
    /// true if result was served from cache
    #[prost(bool, tag="5")]
    pub cache_hit: bool,
    #[prost(double, tag="6")]
    pub latency_ms: f64,
}
/// MemoryEvent records a read or write to the agent's memory store.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MemoryEvent {
    /// "short_term" | "long_term" | "episodic" | "semantic"
    #[prost(string, tag="1")]
    pub memory_type: ::prost::alloc::string::String,
    /// "read" | "write" | "delete" | "search"
    #[prost(string, tag="2")]
    pub operation: ::prost::alloc::string::String,
    /// sanitized key/description — PII redacted by collector
    #[prost(string, tag="3")]
    pub key_summary: ::prost::alloc::string::String,
    #[prost(int32, tag="4")]
    pub entries_affected: i32,
}
/// HandoffEvent records an agent-to-agent delegation of a task or sub-task.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct HandoffEvent {
    #[prost(string, tag="1")]
    pub from_agent_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub to_agent_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub handoff_reason: ::prost::alloc::string::String,
    /// COMPLETED = handoff accepted; FAILURE = rejected
    #[prost(enumeration="CompletionStatus", tag="4")]
    pub status: i32,
    /// sanitized summary of context passed to receiving agent
    #[prost(string, tag="5")]
    pub context_summary: ::prost::alloc::string::String,
}
/// PolicyEvent records the evaluation of a policy bundle against a proposed action.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PolicyEvent {
    #[prost(string, tag="1")]
    pub policy_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub bundle_version: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub action_evaluated: ::prost::alloc::string::String,
    /// "allow" | "block" | "require_approval"
    #[prost(string, tag="4")]
    pub verdict: ::prost::alloc::string::String,
    /// IDs of individual rules that fired
    #[prost(string, repeated, tag="5")]
    pub rules_triggered: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
}
/// InterventionEvent records a system or human intervention that interrupted normal agent flow.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InterventionEvent {
    /// "circuit_break" | "rollback" | "escalate_human" | "model_swap" | "autonomy_downgrade"
    #[prost(string, tag="1")]
    pub intervention_type: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub trigger_reason: ::prost::alloc::string::String,
    /// metric that breached threshold, if system-triggered
    #[prost(string, tag="3")]
    pub trigger_metric_id: ::prost::alloc::string::String,
    /// true = system-triggered; false = human-triggered
    #[prost(bool, tag="4")]
    pub automated: bool,
}
/// RecoveryEvent records a recovery attempt following a failure or intervention.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RecoveryEvent {
    /// "retry" | "fallback" | "rollback" | "restart"
    #[prost(string, tag="1")]
    pub recovery_type: ::prost::alloc::string::String,
    /// error code or short description of what failed
    #[prost(string, tag="2")]
    pub from_error: ::prost::alloc::string::String,
    #[prost(bool, tag="3")]
    pub succeeded: bool,
    /// 1-indexed; >1 means this is a retry
    #[prost(int32, tag="4")]
    pub attempt_number: i32,
}
/// StateSnapshotEvent records a point-in-time capture of agent working state.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct StateSnapshotEvent {
    /// "checkpoint" | "pre_tool" | "post_tool" | "on_error"
    #[prost(string, tag="1")]
    pub snapshot_type: ::prost::alloc::string::String,
    #[prost(int64, tag="2")]
    pub state_size_bytes: i64,
    #[prost(string, tag="3")]
    pub snapshot_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum EventType {
    Unspecified = 0,
    TaskStarted = 1,
    TaskCompleted = 2,
    TaskFailed = 3,
    StepStarted = 4,
    StepCompleted = 5,
    DecisionMade = 6,
    ToolCalled = 7,
    ToolReturned = 8,
    RetrievalPerformed = 9,
    MemoryRead = 10,
    MemoryWritten = 11,
    HandoffInitiated = 12,
    HandoffAccepted = 13,
    PolicyEvaluated = 14,
    InterventionTriggered = 15,
    RecoveryAttempted = 16,
    StateSnapshotCaptured = 17,
}
impl EventType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "EVENT_TYPE_UNSPECIFIED",
            Self::TaskStarted => "TASK_STARTED",
            Self::TaskCompleted => "TASK_COMPLETED",
            Self::TaskFailed => "TASK_FAILED",
            Self::StepStarted => "STEP_STARTED",
            Self::StepCompleted => "STEP_COMPLETED",
            Self::DecisionMade => "DECISION_MADE",
            Self::ToolCalled => "TOOL_CALLED",
            Self::ToolReturned => "TOOL_RETURNED",
            Self::RetrievalPerformed => "RETRIEVAL_PERFORMED",
            Self::MemoryRead => "MEMORY_READ",
            Self::MemoryWritten => "MEMORY_WRITTEN",
            Self::HandoffInitiated => "HANDOFF_INITIATED",
            Self::HandoffAccepted => "HANDOFF_ACCEPTED",
            Self::PolicyEvaluated => "POLICY_EVALUATED",
            Self::InterventionTriggered => "INTERVENTION_TRIGGERED",
            Self::RecoveryAttempted => "RECOVERY_ATTEMPTED",
            Self::StateSnapshotCaptured => "STATE_SNAPSHOT_CAPTURED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "EVENT_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "TASK_STARTED" => Some(Self::TaskStarted),
            "TASK_COMPLETED" => Some(Self::TaskCompleted),
            "TASK_FAILED" => Some(Self::TaskFailed),
            "STEP_STARTED" => Some(Self::StepStarted),
            "STEP_COMPLETED" => Some(Self::StepCompleted),
            "DECISION_MADE" => Some(Self::DecisionMade),
            "TOOL_CALLED" => Some(Self::ToolCalled),
            "TOOL_RETURNED" => Some(Self::ToolReturned),
            "RETRIEVAL_PERFORMED" => Some(Self::RetrievalPerformed),
            "MEMORY_READ" => Some(Self::MemoryRead),
            "MEMORY_WRITTEN" => Some(Self::MemoryWritten),
            "HANDOFF_INITIATED" => Some(Self::HandoffInitiated),
            "HANDOFF_ACCEPTED" => Some(Self::HandoffAccepted),
            "POLICY_EVALUATED" => Some(Self::PolicyEvaluated),
            "INTERVENTION_TRIGGERED" => Some(Self::InterventionTriggered),
            "RECOVERY_ATTEMPTED" => Some(Self::RecoveryAttempted),
            "STATE_SNAPSHOT_CAPTURED" => Some(Self::StateSnapshotCaptured),
            _ => None,
        }
    }
}
/// SemanticConvention maps a typed proto field to its OTel span attribute key.
/// Read by the SDK code generator to emit the right attribute keys.
/// Read by routeiq_validator (collector component) to validate incoming spans.
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SemanticConvention {
    /// e.g. "TaskEvent.completion_status"
    #[prost(string, tag="1")]
    pub proto_field_path: ::prost::alloc::string::String,
    /// e.g. "routeiq.task.completion_status"
    #[prost(string, tag="2")]
    pub otel_attribute_key: ::prost::alloc::string::String,
    #[prost(enumeration="AttributeType", tag="3")]
    pub r#type: i32,
    #[prost(bool, tag="4")]
    pub required: bool,
}
/// ConventionRegistry is the root message for conventions/telemetry.yaml.
/// Every AgentEvent field that appears on the wire must have an entry here.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ConventionRegistry {
    #[prost(message, repeated, tag="1")]
    pub conventions: ::prost::alloc::vec::Vec<SemanticConvention>,
}
// @@protoc_insertion_point(module)
