// @generated
// This file is @generated by prost-build.
/// MetricDefinition is the canonical declaration of a single derived metric.
/// Lives in routeiq-catalog as YAML; this proto defines the shape only.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct MetricDefinition {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub display_name: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub description: ::prost::alloc::string::String,
    #[prost(enumeration="Layer", tag="4")]
    pub layer: i32,
    #[prost(enumeration="EvidenceClass", tag="5")]
    pub evidence_class: i32,
    #[prost(message, repeated, tag="6")]
    pub inputs: ::prost::alloc::vec::Vec<MetricInput>,
    #[prost(message, optional, tag="7")]
    pub formula: ::core::option::Option<Formula>,
    #[prost(string, tag="8")]
    pub unit: ::prost::alloc::string::String,
    #[prost(enumeration="Aggregation", tag="9")]
    pub default_aggregation: i32,
    #[prost(message, repeated, tag="10")]
    pub slo_templates: ::prost::alloc::vec::Vec<SloTemplate>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct MetricInput {
    #[prost(enumeration="super::telemetry::EventType", repeated, tag="1")]
    pub event_types: ::prost::alloc::vec::Vec<i32>,
    #[prost(string, repeated, tag="2")]
    pub field_paths: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(string, tag="3")]
    pub filter: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SloTemplate {
    #[prost(string, tag="1")]
    pub tier: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub target: ::prost::alloc::string::String,
}
/// Formula is the computation declaration for a metric. Exactly one kind is set.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Formula {
    #[prost(oneof="formula::Kind", tags="1, 2, 3, 4")]
    pub kind: ::core::option::Option<formula::Kind>,
}
/// Nested message and enum types in `Formula`.
pub mod formula {
    #[derive(Clone, PartialEq, ::prost::Oneof)]
    pub enum Kind {
        #[prost(message, tag="1")]
        Deterministic(super::DeterministicFormula),
        #[prost(message, tag="2")]
        Heuristic(super::HeuristicFormula),
        #[prost(message, tag="3")]
        Semantic(super::SemanticFormula),
        #[prost(message, tag="4")]
        Frontier(super::FrontierFormula),
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeterministicFormula {
    #[prost(string, tag="1")]
    pub expression: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct HeuristicFormula {
    #[prost(string, tag="1")]
    pub detector_id: ::prost::alloc::string::String,
    #[prost(map="string, string", tag="2")]
    pub parameters: ::std::collections::HashMap<::prost::alloc::string::String, ::prost::alloc::string::String>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SemanticFormula {
    #[prost(string, tag="1")]
    pub classifier_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub operation: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct FrontierFormula {
    #[prost(string, tag="1")]
    pub judge_model: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub rubric_id: ::prost::alloc::string::String,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Layer {
    Unspecified = 0,
    Layer0Runtime = 1,
    Layer1AgentBehavior = 2,
    Layer2Quality = 3,
    Layer3Business = 4,
    Layer4Governance = 5,
}
impl Layer {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "LAYER_UNSPECIFIED",
            Self::Layer0Runtime => "LAYER_0_RUNTIME",
            Self::Layer1AgentBehavior => "LAYER_1_AGENT_BEHAVIOR",
            Self::Layer2Quality => "LAYER_2_QUALITY",
            Self::Layer3Business => "LAYER_3_BUSINESS",
            Self::Layer4Governance => "LAYER_4_GOVERNANCE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "LAYER_UNSPECIFIED" => Some(Self::Unspecified),
            "LAYER_0_RUNTIME" => Some(Self::Layer0Runtime),
            "LAYER_1_AGENT_BEHAVIOR" => Some(Self::Layer1AgentBehavior),
            "LAYER_2_QUALITY" => Some(Self::Layer2Quality),
            "LAYER_3_BUSINESS" => Some(Self::Layer3Business),
            "LAYER_4_GOVERNANCE" => Some(Self::Layer4Governance),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum EvidenceClass {
    EvidenceUnspecified = 0,
    OtelDirect = 1,
    Heuristic = 2,
    Semantic = 3,
    Frontier = 4,
}
impl EvidenceClass {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::EvidenceUnspecified => "EVIDENCE_UNSPECIFIED",
            Self::OtelDirect => "OTEL_DIRECT",
            Self::Heuristic => "HEURISTIC",
            Self::Semantic => "SEMANTIC",
            Self::Frontier => "FRONTIER",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "EVIDENCE_UNSPECIFIED" => Some(Self::EvidenceUnspecified),
            "OTEL_DIRECT" => Some(Self::OtelDirect),
            "HEURISTIC" => Some(Self::Heuristic),
            "SEMANTIC" => Some(Self::Semantic),
            "FRONTIER" => Some(Self::Frontier),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Aggregation {
    Unspecified = 0,
    Avg = 1,
    Sum = 2,
    Count = 3,
    Rate = 4,
    P50 = 5,
    P90 = 6,
    P95 = 7,
    P99 = 8,
    Max = 9,
    Min = 10,
    Last = 11,
}
impl Aggregation {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "AGGREGATION_UNSPECIFIED",
            Self::Avg => "AVG",
            Self::Sum => "SUM",
            Self::Count => "COUNT",
            Self::Rate => "RATE",
            Self::P50 => "P50",
            Self::P90 => "P90",
            Self::P95 => "P95",
            Self::P99 => "P99",
            Self::Max => "MAX",
            Self::Min => "MIN",
            Self::Last => "LAST",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "AGGREGATION_UNSPECIFIED" => Some(Self::Unspecified),
            "AVG" => Some(Self::Avg),
            "SUM" => Some(Self::Sum),
            "COUNT" => Some(Self::Count),
            "RATE" => Some(Self::Rate),
            "P50" => Some(Self::P50),
            "P90" => Some(Self::P90),
            "P95" => Some(Self::P95),
            "P99" => Some(Self::P99),
            "MAX" => Some(Self::Max),
            "MIN" => Some(Self::Min),
            "LAST" => Some(Self::Last),
            _ => None,
        }
    }
}
// @@protoc_insertion_point(module)
