// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Organization {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    #[prost(enumeration="Tier", tag="3")]
    pub tier: i32,
    #[prost(message, optional, tag="4")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, repeated, tag="5")]
    pub workspaces: ::prost::alloc::vec::Vec<Workspace>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Workspace {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub organization_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub environment: ::prost::alloc::string::String,
    #[prost(enumeration="Region", tag="5")]
    pub region: i32,
    #[prost(message, optional, tag="6")]
    pub retention: ::core::option::Option<RetentionConfig>,
}
#[derive(Clone, Copy, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RetentionConfig {
    #[prost(int32, tag="1")]
    pub hot_days: i32,
    #[prost(int32, tag="2")]
    pub warm_days: i32,
    #[prost(int32, tag="3")]
    pub cold_days: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateOrganizationRequest {
    #[prost(string, tag="1")]
    pub name: ::prost::alloc::string::String,
    #[prost(enumeration="Tier", tag="2")]
    pub tier: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetOrganizationRequest {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListOrganizationsRequest {
    #[prost(int32, tag="1")]
    pub page_size: i32,
    #[prost(string, tag="2")]
    pub page_token: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListOrganizationsResponse {
    #[prost(message, repeated, tag="1")]
    pub organizations: ::prost::alloc::vec::Vec<Organization>,
    #[prost(string, tag="2")]
    pub next_page_token: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateOrganizationRequest {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    #[prost(enumeration="Tier", tag="3")]
    pub tier: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteOrganizationRequest {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateWorkspaceRequest {
    #[prost(string, tag="1")]
    pub organization_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub environment: ::prost::alloc::string::String,
    #[prost(enumeration="Region", tag="4")]
    pub region: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListWorkspacesRequest {
    #[prost(string, tag="1")]
    pub organization_id: ::prost::alloc::string::String,
    #[prost(int32, tag="2")]
    pub page_size: i32,
    #[prost(string, tag="3")]
    pub page_token: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListWorkspacesResponse {
    #[prost(message, repeated, tag="1")]
    pub workspaces: ::prost::alloc::vec::Vec<Workspace>,
    #[prost(string, tag="2")]
    pub next_page_token: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct UpdateWorkspaceRequest {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub name: ::prost::alloc::string::String,
    #[prost(message, optional, tag="3")]
    pub retention: ::core::option::Option<RetentionConfig>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Tier {
    Unspecified = 0,
    Free = 1,
    Growth = 2,
    Pro = 3,
    Enterprise = 4,
}
impl Tier {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "TIER_UNSPECIFIED",
            Self::Free => "FREE",
            Self::Growth => "GROWTH",
            Self::Pro => "PRO",
            Self::Enterprise => "ENTERPRISE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "TIER_UNSPECIFIED" => Some(Self::Unspecified),
            "FREE" => Some(Self::Free),
            "GROWTH" => Some(Self::Growth),
            "PRO" => Some(Self::Pro),
            "ENTERPRISE" => Some(Self::Enterprise),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Region {
    Unspecified = 0,
    UsEast1 = 1,
    UsWest2 = 2,
    EuWest1 = 3,
    ApSoutheast1 = 4,
}
impl Region {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "REGION_UNSPECIFIED",
            Self::UsEast1 => "US_EAST_1",
            Self::UsWest2 => "US_WEST_2",
            Self::EuWest1 => "EU_WEST_1",
            Self::ApSoutheast1 => "AP_SOUTHEAST_1",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "REGION_UNSPECIFIED" => Some(Self::Unspecified),
            "US_EAST_1" => Some(Self::UsEast1),
            "US_WEST_2" => Some(Self::UsWest2),
            "EU_WEST_1" => Some(Self::EuWest1),
            "AP_SOUTHEAST_1" => Some(Self::ApSoutheast1),
            _ => None,
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct UsageSummary {
    #[prost(string, tag="1")]
    pub organization_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag="2")]
    pub period_start: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag="3")]
    pub period_end: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(int64, tag="4")]
    pub events_ingested: i64,
    #[prost(int64, tag="5")]
    pub metrics_evaluated: i64,
    #[prost(int64, tag="6")]
    pub frontier_judge_calls: i64,
    #[prost(double, tag="7")]
    pub total_cost_usd: f64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct Quota {
    #[prost(string, tag="1")]
    pub organization_id: ::prost::alloc::string::String,
    #[prost(enumeration="Tier", tag="2")]
    pub tier: i32,
    #[prost(int64, tag="3")]
    pub events_per_month: i64,
    #[prost(int64, tag="4")]
    pub frontier_calls_per_month: i64,
    #[prost(int64, tag="5")]
    pub retention_days: i64,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetUsageRequest {
    #[prost(string, tag="1")]
    pub organization_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag="2")]
    pub period_start: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag="3")]
    pub period_end: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetQuotaRequest {
    #[prost(string, tag="1")]
    pub organization_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct User {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub email: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub display_name: ::prost::alloc::string::String,
    #[prost(enumeration="AuthProvider", tag="4")]
    pub auth_provider: i32,
    #[prost(message, optional, tag="5")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RoleAssignment {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub organization_id: ::prost::alloc::string::String,
    #[prost(enumeration="Role", tag="3")]
    pub role: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ApiKey {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub organization_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub workspace_id: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub prefix: ::prost::alloc::string::String,
    #[prost(enumeration="ApiKeyScope", tag="5")]
    pub scope: i32,
    #[prost(message, optional, tag="6")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(message, optional, tag="7")]
    pub expires_at: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct InviteUserRequest {
    #[prost(string, tag="1")]
    pub organization_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub email: ::prost::alloc::string::String,
    #[prost(enumeration="Role", tag="3")]
    pub role: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetUserRequest {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct AssignRoleRequest {
    #[prost(string, tag="1")]
    pub user_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub organization_id: ::prost::alloc::string::String,
    #[prost(enumeration="Role", tag="3")]
    pub role: i32,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreateApiKeyRequest {
    #[prost(string, tag="1")]
    pub organization_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub workspace_id: ::prost::alloc::string::String,
    #[prost(enumeration="ApiKeyScope", tag="3")]
    pub scope: i32,
    #[prost(message, optional, tag="4")]
    pub expires_at: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct RevokeApiKeyRequest {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListApiKeysRequest {
    #[prost(string, tag="1")]
    pub organization_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub workspace_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListApiKeysResponse {
    #[prost(message, repeated, tag="1")]
    pub api_keys: ::prost::alloc::vec::Vec<ApiKey>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Role {
    Unspecified = 0,
    Viewer = 1,
    Analyst = 2,
    Admin = 3,
    Owner = 4,
}
impl Role {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "ROLE_UNSPECIFIED",
            Self::Viewer => "VIEWER",
            Self::Analyst => "ANALYST",
            Self::Admin => "ADMIN",
            Self::Owner => "OWNER",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ROLE_UNSPECIFIED" => Some(Self::Unspecified),
            "VIEWER" => Some(Self::Viewer),
            "ANALYST" => Some(Self::Analyst),
            "ADMIN" => Some(Self::Admin),
            "OWNER" => Some(Self::Owner),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum AuthProvider {
    Unspecified = 0,
    Google = 1,
    Github = 2,
    Saml = 3,
}
impl AuthProvider {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "AUTH_PROVIDER_UNSPECIFIED",
            Self::Google => "GOOGLE",
            Self::Github => "GITHUB",
            Self::Saml => "SAML",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "AUTH_PROVIDER_UNSPECIFIED" => Some(Self::Unspecified),
            "GOOGLE" => Some(Self::Google),
            "GITHUB" => Some(Self::Github),
            "SAML" => Some(Self::Saml),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum ApiKeyScope {
    Unspecified = 0,
    IngestOnly = 1,
    IngestAndControl = 2,
    AdminScope = 3,
}
impl ApiKeyScope {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "API_KEY_SCOPE_UNSPECIFIED",
            Self::IngestOnly => "INGEST_ONLY",
            Self::IngestAndControl => "INGEST_AND_CONTROL",
            Self::AdminScope => "ADMIN_SCOPE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "API_KEY_SCOPE_UNSPECIFIED" => Some(Self::Unspecified),
            "INGEST_ONLY" => Some(Self::IngestOnly),
            "INGEST_AND_CONTROL" => Some(Self::IngestAndControl),
            "ADMIN_SCOPE" => Some(Self::AdminScope),
            _ => None,
        }
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct PolicyBundle {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub organization_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub workspace_id: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub version: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="5")]
    pub content: ::prost::alloc::vec::Vec<u8>,
    #[prost(bool, tag="6")]
    pub active: bool,
    #[prost(message, optional, tag="7")]
    pub created_at: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct CreatePolicyBundleRequest {
    #[prost(string, tag="1")]
    pub organization_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub workspace_id: ::prost::alloc::string::String,
    #[prost(bytes="vec", tag="3")]
    pub content: ::prost::alloc::vec::Vec<u8>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetPolicyBundleRequest {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ListPolicyBundlesRequest {
    #[prost(string, tag="1")]
    pub workspace_id: ::prost::alloc::string::String,
    #[prost(bool, tag="2")]
    pub active_only: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct ListPolicyBundlesResponse {
    #[prost(message, repeated, tag="1")]
    pub bundles: ::prost::alloc::vec::Vec<PolicyBundle>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct ActivatePolicyBundleRequest {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeletePolicyBundleRequest {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SloOverride {
    #[prost(string, tag="1")]
    pub metric_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub workspace_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub tier: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub target_expression: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SloOverrides {
    #[prost(string, tag="1")]
    pub workspace_id: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="2")]
    pub overrides: ::prost::alloc::vec::Vec<SloOverride>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct GetSloOverridesRequest {
    #[prost(string, tag="1")]
    pub workspace_id: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SetSloOverrideRequest {
    #[prost(message, optional, tag="1")]
    pub r#override: ::core::option::Option<SloOverride>,
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DeleteSloOverrideRequest {
    #[prost(string, tag="1")]
    pub metric_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub workspace_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub tier: ::prost::alloc::string::String,
}
// @@protoc_insertion_point(module)
