// @generated
// This file is @generated by prost-build.
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct AlertRule {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub metric_id: ::prost::alloc::string::String,
    #[prost(message, optional, tag="3")]
    pub condition: ::core::option::Option<Condition>,
    #[prost(enumeration="Severity", tag="4")]
    pub severity: i32,
    #[prost(enumeration="RecommendedAction", repeated, tag="5")]
    pub actions: ::prost::alloc::vec::Vec<i32>,
    #[prost(string, tag="6")]
    pub description: ::prost::alloc::string::String,
    #[prost(bool, tag="7")]
    pub enabled: bool,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Condition {
    #[prost(enumeration="Operator", tag="1")]
    pub op: i32,
    #[prost(double, tag="2")]
    pub threshold: f64,
    #[prost(string, tag="3")]
    pub window: ::prost::alloc::string::String,
    #[prost(int32, tag="4")]
    pub min_samples: i32,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Operator {
    Unspecified = 0,
    Gt = 1,
    Lt = 2,
    Gte = 3,
    Lte = 4,
    Eq = 5,
    TrendUp = 6,
    TrendDown = 7,
}
impl Operator {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "OPERATOR_UNSPECIFIED",
            Self::Gt => "GT",
            Self::Lt => "LT",
            Self::Gte => "GTE",
            Self::Lte => "LTE",
            Self::Eq => "EQ",
            Self::TrendUp => "TREND_UP",
            Self::TrendDown => "TREND_DOWN",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "OPERATOR_UNSPECIFIED" => Some(Self::Unspecified),
            "GT" => Some(Self::Gt),
            "LT" => Some(Self::Lt),
            "GTE" => Some(Self::Gte),
            "LTE" => Some(Self::Lte),
            "EQ" => Some(Self::Eq),
            "TREND_UP" => Some(Self::TrendUp),
            "TREND_DOWN" => Some(Self::TrendDown),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum Severity {
    Unspecified = 0,
    Info = 1,
    Warning = 2,
    Critical = 3,
    Page = 4,
}
impl Severity {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "SEVERITY_UNSPECIFIED",
            Self::Info => "INFO",
            Self::Warning => "WARNING",
            Self::Critical => "CRITICAL",
            Self::Page => "PAGE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SEVERITY_UNSPECIFIED" => Some(Self::Unspecified),
            "INFO" => Some(Self::Info),
            "WARNING" => Some(Self::Warning),
            "CRITICAL" => Some(Self::Critical),
            "PAGE" => Some(Self::Page),
            _ => None,
        }
    }
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum RecommendedAction {
    ActionUnspecified = 0,
    ReduceAutonomy = 1,
    CircuitBreak = 2,
    EscalateHuman = 3,
    RollbackVersion = 4,
    SwitchModel = 5,
    RequireApproval = 6,
}
impl RecommendedAction {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::ActionUnspecified => "ACTION_UNSPECIFIED",
            Self::ReduceAutonomy => "REDUCE_AUTONOMY",
            Self::CircuitBreak => "CIRCUIT_BREAK",
            Self::EscalateHuman => "ESCALATE_HUMAN",
            Self::RollbackVersion => "ROLLBACK_VERSION",
            Self::SwitchModel => "SWITCH_MODEL",
            Self::RequireApproval => "REQUIRE_APPROVAL",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "ACTION_UNSPECIFIED" => Some(Self::ActionUnspecified),
            "REDUCE_AUTONOMY" => Some(Self::ReduceAutonomy),
            "CIRCUIT_BREAK" => Some(Self::CircuitBreak),
            "ESCALATE_HUMAN" => Some(Self::EscalateHuman),
            "ROLLBACK_VERSION" => Some(Self::RollbackVersion),
            "SWITCH_MODEL" => Some(Self::SwitchModel),
            "REQUIRE_APPROVAL" => Some(Self::RequireApproval),
            _ => None,
        }
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct DashboardWidget {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub title: ::prost::alloc::string::String,
    #[prost(string, repeated, tag="3")]
    pub metric_ids: ::prost::alloc::vec::Vec<::prost::alloc::string::String>,
    #[prost(enumeration="WidgetType", tag="4")]
    pub r#type: i32,
    #[prost(string, tag="5")]
    pub default_range: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct Dashboard {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub title: ::prost::alloc::string::String,
    #[prost(message, repeated, tag="3")]
    pub widgets: ::prost::alloc::vec::Vec<DashboardWidget>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum WidgetType {
    Unspecified = 0,
    Gauge = 1,
    Timeseries = 2,
    Table = 3,
    Heatmap = 4,
    Sparkline = 5,
}
impl WidgetType {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "WIDGET_TYPE_UNSPECIFIED",
            Self::Gauge => "GAUGE",
            Self::Timeseries => "TIMESERIES",
            Self::Table => "TABLE",
            Self::Heatmap => "HEATMAP",
            Self::Sparkline => "SPARKLINE",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "WIDGET_TYPE_UNSPECIFIED" => Some(Self::Unspecified),
            "GAUGE" => Some(Self::Gauge),
            "TIMESERIES" => Some(Self::Timeseries),
            "TABLE" => Some(Self::Table),
            "HEATMAP" => Some(Self::Heatmap),
            "SPARKLINE" => Some(Self::Sparkline),
            _ => None,
        }
    }
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct InterventionRecommendation {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub alert_rule_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub metric_id: ::prost::alloc::string::String,
    #[prost(enumeration="RecommendedAction", tag="4")]
    pub action: i32,
    #[prost(string, tag="5")]
    pub rationale: ::prost::alloc::string::String,
    #[prost(double, tag="6")]
    pub confidence: f64,
    #[prost(message, optional, tag="7")]
    pub generated_at: ::core::option::Option<::prost_types::Timestamp>,
    #[prost(enumeration="InterventionStatus", tag="8")]
    pub status: i32,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum InterventionStatus {
    Unspecified = 0,
    Pending = 1,
    Applied = 2,
    Dismissed = 3,
    Expired = 4,
}
impl InterventionStatus {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "INTERVENTION_STATUS_UNSPECIFIED",
            Self::Pending => "PENDING",
            Self::Applied => "APPLIED",
            Self::Dismissed => "DISMISSED",
            Self::Expired => "EXPIRED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "INTERVENTION_STATUS_UNSPECIFIED" => Some(Self::Unspecified),
            "PENDING" => Some(Self::Pending),
            "APPLIED" => Some(Self::Applied),
            "DISMISSED" => Some(Self::Dismissed),
            "EXPIRED" => Some(Self::Expired),
            _ => None,
        }
    }
}
#[derive(Clone, PartialEq, Eq, Hash, ::prost::Message)]
pub struct SloTarget {
    #[prost(string, tag="1")]
    pub id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub metric_id: ::prost::alloc::string::String,
    #[prost(string, tag="3")]
    pub workspace_id: ::prost::alloc::string::String,
    #[prost(string, tag="4")]
    pub tier: ::prost::alloc::string::String,
    #[prost(string, tag="5")]
    pub target_expression: ::prost::alloc::string::String,
    #[prost(string, tag="6")]
    pub window: ::prost::alloc::string::String,
}
#[derive(Clone, PartialEq, ::prost::Message)]
pub struct SloStatus {
    #[prost(string, tag="1")]
    pub slo_id: ::prost::alloc::string::String,
    #[prost(string, tag="2")]
    pub metric_id: ::prost::alloc::string::String,
    #[prost(double, tag="3")]
    pub current_value: f64,
    #[prost(double, tag="4")]
    pub target_value: f64,
    #[prost(enumeration="SloState", tag="5")]
    pub state: i32,
    #[prost(double, tag="6")]
    pub error_budget_remaining: f64,
    #[prost(message, optional, tag="7")]
    pub evaluated_at: ::core::option::Option<::prost_types::Timestamp>,
}
#[derive(Clone, Copy, Debug, PartialEq, Eq, Hash, PartialOrd, Ord, ::prost::Enumeration)]
#[repr(i32)]
pub enum SloState {
    Unspecified = 0,
    Meeting = 1,
    AtRisk = 2,
    Breached = 3,
}
impl SloState {
    /// String value of the enum field names used in the ProtoBuf definition.
    ///
    /// The values are not transformed in any way and thus are considered stable
    /// (if the ProtoBuf definition does not change) and safe for programmatic use.
    pub fn as_str_name(&self) -> &'static str {
        match self {
            Self::Unspecified => "SLO_STATE_UNSPECIFIED",
            Self::Meeting => "MEETING",
            Self::AtRisk => "AT_RISK",
            Self::Breached => "BREACHED",
        }
    }
    /// Creates an enum from field names used in the ProtoBuf definition.
    pub fn from_str_name(value: &str) -> ::core::option::Option<Self> {
        match value {
            "SLO_STATE_UNSPECIFIED" => Some(Self::Unspecified),
            "MEETING" => Some(Self::Meeting),
            "AT_RISK" => Some(Self::AtRisk),
            "BREACHED" => Some(Self::Breached),
            _ => None,
        }
    }
}
// @@protoc_insertion_point(module)
